.TH PERU 1
.SH NAME
peru \- modular build tool
.SH SYNOPSIS
.B peru
[\fB\-\-version\fR]
\fICOMMAND\fR [\fIARGS\fR...]
.SH DESCRIPTION
.B peru
builds multi-homed modules and dependencies
.SH OPTIONS
.TP
.BR \-\-version
Prints version information.
.SH COMMANDS
.TP
.BR pull " " [\fB\-\-flush-cache\fR]
Pulls source code and cached binaries to the local workspace.
.TP
.BR build " " [\fB\-\-flush-cache\fR]
Builds the local workspace.
