#! /usr/bin/env python3

import collections
import os
import sys

peru_file_env = {}
# TODO: "build". "deps"?
general_fields = ("name", "dest")


def validate_plugin(name, fields, callback):
    assert None not in (name, fields, callback)
    assert name not in peru_file_env, "Plugin names must be unique: " + name
    overlapping_fields = set(fields) & set(general_fields)
    assert not overlapping_fields, \
        "Field names already taken: " + ", ".join(overlapping_fields)


def validate_module(name, fields, kwargs):
    for field in general_fields + fields:
        assert field in kwargs, \
            "{0} requires a {1} field.".format(name, field)
    for field in kwargs:
        assert field in general_fields + fields, \
            "{0} does not allow a {1} field.".format(name, field)


def peru_register(*, name=None, fields=None, get_files_callback=None):
    validate_plugin(name, fields, get_files_callback)
    def plugin_function(**kwargs):
        print(name)
        validate_module(name, fields, kwargs)
        # TODO: When we have a cache, use that as the target dir instead of the
        # final dest dir.
        dest = kwargs["dest"]
        os.makedirs(dest, exist_ok=True)
        filtered_kwargs = {key: val for key, val in kwargs.items()
                           if key in fields}
        get_files_callback(filtered_kwargs, dest)
    plugin_function.__name__ = name
    peru_file_env[name] = plugin_function


def peru_cache_path():
    # Use $PERU_CACHE_NAME if defined, otherwise use the default root path.
    return os.getenv("PERU_CACHE_NAME") or ".peru-cache"


def plugin_kwargs():
    return {
        "register": peru_register,
        "cache_path": peru_cache_path(),
    }


def main():
    if not os.path.isfile("peru"):
        print("No peru file found.")
        sys.exit(1)

    # TODO: stop hardcoding this
    plugins = ["git_plugin"]
    for plugin_name in plugins:
        # fromlist just needs to be nonempty here. weird.
        plugin = __import__("plugins." + plugin_name, fromlist=["dummy"])
        plugin.peru_plugin_main(**plugin_kwargs())

    peru_file_name = os.getenv("PERU_FILE_NAME") or "peru"
    with open(peru_file_name) as peru_file:
        peru_file_code = peru_file.read()

    # TODO: Should this be an import too?
    exec(peru_file_code, dict(peru_file_env))


if __name__ == "__main__":
    main()
