name: tests

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  test:
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
    - run: git --version
    # Make sure Subversion (including `svnadmin`) and Mercurial are installed
    # on Windows and macOS. I'd prefer `uv tool install mercurial`, but the
    # `hg` binary that that installs crashes on Windows for some reason. We
    # don't need Mercurial to use the same Python version that we're using.
    # Also Choco and WinGet seem to fail to put `hg` in the PATH for some
    # reason.
    - run: pip install mercurial
    - run: sudo apt-get update && sudo apt-get install -y subversion
      if: matrix.os == 'ubuntu-latest'
    - run: brew install subversion
      if: matrix.os == 'macOS-latest'
    - run: choco install -y --no-progress sliksvn
      if: matrix.os == 'windows-latest'
    # Run tests.
    - run: uv run --python ${{ matrix.python-version }} test.py -v
